#line 1 "parser/cpal_lex.c"

#line 3 "parser/cpal_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */

/* %endif */

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* %endif */

/* %if-not-reentrant */
/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

/* %endif */

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	yyg->yy_c_buf_p = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[219] =
    {   0,
        0,    0,    0,    0,    7,    7,   88,   86,   11,   12,
       13,   86,   86,   77,   48,   62,   63,   72,   70,   69,
       71,   68,   73,   84,   84,   75,   74,   60,   54,   61,
       76,   82,   82,   66,   67,   51,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   64,   49,   65,   50,    3,    4,    3,
        3,   87,    7,   10,    9,   12,   13,   56,    0,   85,
        0,    1,    0,    0,   84,    0,    0,    0,   78,    0,
       52,   58,   55,   59,   53,   82,   47,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   26,   15,

       82,   82,   82,   32,   45,   82,   82,   82,   82,   82,
       31,   82,   82,   82,   82,    5,    2,    7,   10,    0,
        0,    9,   83,    0,   80,   79,   78,    0,   81,   82,
       82,   44,   82,   82,   82,   82,   82,   82,   82,   82,
       25,   82,   82,   38,   57,   14,   82,   82,   82,   82,
       82,   82,   21,   82,   82,    8,    0,    0,   82,   82,
       82,   82,   82,   82,   82,   27,   19,   82,   82,   82,
       39,   40,   82,   82,   82,   82,   82,   16,   82,   43,
       82,   33,   41,   82,   82,   18,   82,   17,   82,   82,
       82,   23,   24,   34,   82,   82,   28,   82,   82,   36,

       82,   82,   82,   82,   35,   20,   82,   22,   82,   37,
        6,   29,   46,   42,   82,   82,   30,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,    1,   10,    1,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   27,   27,   27,   28,   27,
       29,   30,   31,   29,   29,   32,   29,   33,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   29,   45,   46,   29,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       67,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    3,    3,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    1,    4,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1,    1,    5
    } ;

static const flex_int16_t yy_base[227] =
    {   0,
        0,    0,   65,   67,   80,    0,  404,  405,  405,    0,
        0,  379,  141,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  389,  172,  341,  405,  405,   49,  376,   50,
      405,    0,  337,  405,  405,  405,  360,  105,  343,  105,
       29,  112,  109,  345,  344,  343,  107,  339,  335,  335,
      115,  351,  122,  405,  405,  405,  405,  405,  405,  386,
      370,  405,  168,  176,    0,    0,    0,  405,  147,  405,
      384,  405,  176,  152,  326,  174,  323,  329,  155,  217,
      405,  405,  405,  405,  405,    0,    0,  351,  326,  339,
      337,  340,  135,  323,  320,  328,  325,  320,    0,  332,

      321,  329,  314,    0,    0,  313,  325,  316,  323,  147,
        0,  308,  310,  317,  306,  405,  405,  193,  201,  205,
      209,    0,  235,  177,  198,  405,  215,  233,  252,  330,
      317,    0,  317,  299,  297,  186,  293,  282,  268,  283,
        0,  273,  268,    0,    0,    0,  265,  277,  260,  158,
      259,  272,    0,  265,  266,  244,  157,  257,  277,  254,
      258,  254,  252,  246,  255,    0,    0,  256,  250,  240,
        0,    0,  246,  244,  239,  204,  243,    0,  238,    0,
      249,    0,    0,  233,  225,    0,  224,    0,  225,  228,
      214,    0,    0,    0,  227,  211,    0,  228,  216,    0,

      192,  169,  180,  164,    0,    0,  172,    0,  161,    0,
        0,  137,    0,    0,  109,   32,    0,  405,  324,  329,
      334,  339,  342,  347,  350,  354
    } ;

static const flex_int16_t yy_def[227] =
    {   0,
      218,    1,  219,  219,  218,    5,  218,  218,  218,  220,
      221,  218,  222,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,   24,  218,  218,  218,  218,  218,
      218,  223,  223,  218,  218,  218,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  224,  225,  220,  221,  218,  222,  218,
      222,  218,  218,  218,   24,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  218,  218,  218,  224,  226,
      226,  225,  218,  218,  218,  218,  218,  218,  218,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  226,  218,  218,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,    0,  218,  218,
      218,  218,  218,  218,  218,  218
    } ;

static const flex_int16_t yy_nxt[473] =
    {   0,
        8,    9,   10,   11,    9,   12,   13,    8,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   32,   32,   33,
       32,   32,   32,   34,    8,   35,   36,   37,   38,   39,
       40,   32,   41,   42,   32,   43,   32,   44,   45,   46,
       47,   48,   49,   32,   50,   51,   32,   52,   53,   32,
       32,   32,   54,   55,   56,   57,   32,   59,   60,   59,
       60,   81,   82,   84,   85,  217,   94,   61,   95,   61,
       62,   63,   62,   62,   63,   62,   64,   65,   62,   62,
       62,   62,   62,   62,   62,   62,   65,   65,   65,   65,

       62,   62,   62,   62,   62,   62,   65,   65,   65,   65,
       65,   65,   65,   62,   65,   62,   62,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   62,   62,   62,   62,   62,   70,   89,   92,
       96,  216,   99,   70,   90,   93,  104,   97,  100,  127,
      105,  157,   98,  106,  107,  111,  114,  115,  112,  118,
      123,  123,  118,  128,  128,   71,   73,  120,  215,  120,
       73,   71,  121,  135,  136,  150,   77,  124,   74,  124,
       75,   75,  125,  125,  118,  125,  125,  118,  175,   76,

      151,   77,  120,  214,  120,   77,  120,  156,  120,  213,
      120,  156,  120,  176,   76,  156,  125,  125,  212,  127,
       78,   78,  211,   78,   78,   78,   79,   78,   78,  210,
       79,   80,   78,  128,  128,  129,  129,  158,   78,  157,
      164,  165,   78,  129,  129,  120,  194,  120,  209,  195,
      156,  128,  128,  123,  123,  129,  129,  129,  129,  129,
      129,  158,   76,  208,   77,  207,  206,  205,  204,  203,
      129,  129,  202,  201,  200,  199,  198,   76,  129,  129,
      197,   78,   78,  196,   78,  193,  192,   79,  191,   78,
      129,  129,  129,  129,  129,  129,  190,  189,  188,   78,

      187,  186,  185,  184,  183,   78,   78,  182,   78,  181,
      180,   79,  179,   78,  178,  177,  174,  173,  172,  171,
      170,  169,  168,   78,   58,   58,   58,   58,   58,   66,
      167,   66,   66,   66,   67,  166,   67,   67,   67,   69,
       69,   69,   69,   69,   86,  163,   86,  119,  162,  119,
      119,  119,  122,  122,  121,  161,  121,  121,  121,  160,
      159,  155,  154,  153,  152,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  138,  137,  134,  133,
      132,  131,  130,   79,  126,  218,  218,  117,  116,  113,
      110,  109,  108,  103,  102,  101,   91,   88,   87,   83,

      218,   72,   68,  218,    7,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218
    } ;

static const flex_int16_t yy_chk[473] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    4,
        4,   28,   28,   30,   30,  216,   41,    3,   41,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,   13,   38,   40,
       42,  215,   43,   69,   38,   40,   47,   42,   43,   79,
       47,  157,   42,   47,   47,   51,   53,   53,   51,   63,
       74,   74,   63,   79,   79,   13,   24,   64,  212,   64,
       73,   69,   64,   93,   93,  110,  157,   76,   24,   76,
       24,   24,   76,   76,  118,  124,  124,  118,  150,   24,

      110,   24,  119,  209,  119,   73,  120,  119,  120,  207,
      121,  120,  121,  150,   24,  121,  125,  125,  204,  127,
       24,   24,  203,   24,   73,   73,   24,   73,   24,  202,
       73,   24,   73,  127,  127,   80,   80,  128,   24,  123,
      136,  136,   73,   80,   80,  156,  176,  156,  201,  176,
      156,  128,  128,  123,  123,   80,   80,   80,   80,   80,
       80,  158,  123,  199,  123,  198,  196,  195,  191,  190,
      129,  129,  189,  187,  185,  184,  181,  123,  129,  129,
      179,  128,  128,  177,  128,  175,  174,  128,  173,  128,
      129,  129,  129,  129,  129,  129,  170,  169,  168,  128,

      165,  164,  163,  162,  161,  158,  158,  160,  158,  159,
      155,  158,  154,  158,  152,  151,  149,  148,  147,  143,
      142,  140,  139,  158,  219,  219,  219,  219,  219,  220,
      138,  220,  220,  220,  221,  137,  221,  221,  221,  222,
      222,  222,  222,  222,  223,  135,  223,  224,  134,  224,
      224,  224,  225,  225,  226,  133,  226,  226,  226,  131,
      130,  115,  114,  113,  112,  109,  108,  107,  106,  103,
      102,  101,  100,   98,   97,   96,   95,   94,   92,   91,
       90,   89,   88,   78,   77,   75,   71,   61,   60,   52,
       50,   49,   48,   46,   45,   44,   39,   37,   33,   29,

       25,   23,   12,    7,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[88] =
    {   0,
0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0,     };

static const flex_int16_t yy_rule_linenum[87] =
    {   0,
      229,  230,  231,  232,  233,  237,  238,  239,  240,  243,
      274,  275,  284,  293,  294,  295,  296,  297,  298,  299,
      300,  301,  302,  303,  304,  305,  306,  307,  308,  309,
      310,  311,  312,  313,  314,  315,  316,  317,  318,  319,
      320,  321,  322,  323,  324,  325,  326,  327,  328,  329,
      330,  331,  332,  333,  334,  335,  336,  337,  338,  339,
      340,  341,  342,  343,  344,  345,  346,  347,  348,  349,
      350,  351,  352,  353,  354,  355,  356,  357,  358,  359,
      360,  361,  362,  363,  364,  365
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "parser/cpal_lex.l"
/* A (f)lex file defines a lexical analyzer (also called lexer or
   scanner, we will use the word scanner in the following even though
   all three are in common use) and additional utility functions
   associated to it.  In the following, we'll summarily describe its
   syntax with the help of comments like this, focusing on flex and
   without highlighting the differences with respect to traditional
   lex.

   A flex file is divided into three sections, separated by a line
   that contains only %% at column 1.  The separator can be omitted if
   the section that would follow it is empty.  This comment is in the
   first section of the file.
*/
/* The first section of the file is called "definitions section" in
   the flex manual and contains 4 important subsections.  All of them
   are optional, but quite useful.

   The first subsection is immediately after this comment.  It
   consists of a fragment of C code, enclosed in %{ and %} at the very
   beginning of a line, which flex copies verbatim into the C source
   file it generates.  As can be seen below, its typical purposes are:

   1- Include header files containing definitions (macros, data types,
      function prototypes) used by the C code fragments associated to
      the regular expressions given in the second section.  If the
      scanner is meant to be used with a parser, then, a very
      important one among them is a header generated by the parser
      generator (bison or yacc) that acts as the interface between the
      scanner and the parser.  It mainly contains the definition of an
      enumerated data type for token types (enum yytokentype).

   Implementation notes: In this case, since the header files that are
   included here are part of the standard CPAL toolset, we will
   remove/replace them with our own.  The exception is cpal_parser.h
   that, as said previously, is generated by bison.

   2- Declare the prototype of any function defined in the third
      section of this file.  This is necessary in order to use those
      functions in the C code fragments associated to the regular
      expressions (second section of this file) without incurring in
      compiler warnings.

   Implementation note: An example is the prototype of the include()
   function.
*/
#line 49 "parser/cpal_lex.l"
#include "parser_config.h"
#include "rENV.h"
#include "lex_fix.h"
#include "cpal_grammar.h"
#include "rAST.h"
#include "def_expression.h"
#include "def_variable.h"
#include "parser_error.h"
#include "path.h"
#include "parser_interface.h"

void include(yyscan_t scanner,parser_Env * env, char * quoted_filename);
#line 792 "parser/cpal_lex.c"
/* The second sub-part gives some options to flex.  One or more
   options can be given on a line that starts with %option.  Let's
   have a look at the following options one by one:

   - 'reentrant' indicates that (contrary to what traditional lex
     would do), flex should generate a reentrant scanner that can be
     instantiated multiple times and can be used concurrently (in a
     multithreaded environment) or recursively (a scanner can create
     and use another instance of itself while operating) without any
     problem.  See flex manual Chapter 19.

   - 'bison-bridge' indicates that the scanner will be used in
     combination with a parser generated by bison or yacc.  It changes
     the API of the scanner a little bit so that, specifically, it
     supports the yylval argument.  This argument must be used by the
     scanner to pass the semantic value of a token to the parser.
     More information about this in the parser definition file (.y).

   - 'warn' enables warnings

   - 'nodefault' suppresses the default rule that flex would silently
     add to the set of rules specified in the second part of this
     file.  More on this in the section section of this file.

   - 'pointer' says that yytext (the variable that holds a token while
     the scanner builds it from input characters) must be a pointer
     instead of an array.  Traditional lex used an array.  For flex,
     the default is pointer.  Therefore, strictly speaking, this
     option is redundant even though is often included anyway for
     clarity.

     Using a pointer makes the scanner faster and avoids overflowing
     the space statically allocated to the yytext array when parsing
     large tokens, which would be a fatal error.

     The price to be paid is that there are some additional
     restrictions in the use of yytext.  Frankly speaking, this is not
     a big deal because if a piece of code is hit these restrictions
     it is very likely code that "plays tricks" with the scanner
     internals, so its use would be discouraged anyway.  More on this
     topic upon request.  ;)

   - the various 'no'-something options ask flex to not provide its
     own utility functions and possibly let others provide their own.
     For instance:

     - noyyalloc tells flex to not provide its own dynamic memory
     allocation function.  Indeed, a custom yyalloc() is defined in
     the third section of this .l file.

     - nounput asks flex not to provide the function unput().  This
       function can be used by actions associated with regular
       expressions in the second part of this file to "push back" one
       or more characters into the input stream after matching a
       token, so that the same characters are scanned again in the
       future.  In this case, no alternative implementation is
       provided because the scanner does not use this feature.

     For all these functions, no prototype is needed in the first
     section (unlike for include() that we discussed previously)
     because flex provides the prototype anyway and the replacement
     functions must obviously obey it.

   - the yylineno option enables a scanner-level mechanism that keeps
     track of the line number position of each token within the source
     file.  This information allows the scanner and the parser and
     other modules to emit sensible, human-friendly error messages,
     provided this information is propagated to the parser within
     semantic values and then kept in the AST.

   Even though most of these options can also be given directly on the
   flex command line, it is often more convenient to specify them in
   the .l file.  This is because some options deeply affect the way
   flex parses the .l file itself and using inappropriate options may
   lead to subtle errors.  With everything in one place, the scanner
   definition is completely self-contained in the .l file.
*/
#define YY_NO_INPUT 1
/* The third, but extremely important, piece of information given in
   the first section of the .l file is the definition of additional
   start conditions for the scanner, if needed.  Flex always has a
   default start condition called INITIAL.  See Chapter 10 of the
   manual.

   Start conditions can be exclusive (declared by %x) or inclusive
   (declared by %s).  The difference is explained better while
   discussing the second section of the file.

   In summary, when the scanner is in an exclusive start condition, it
   disables regular expressions that are not explicitly tagged by any
   start condition.  On the contrary, when the parser is in an
   inclusive start conditions lets those regular expressions enabled.
   Regular expressions tagged only with start conditions different
   than the one the parser is in, are disabled in both cases.

   Informally speaking, start conditions are used to selectively
   enable or disable groups of regular expressions in the second
   section of the file.  In turn, this is useful to make the scanner
   recognize and build tokens according to different sets of lexical
   rules, depending on its state.  In turn, the state of the parser
   may depend on past input because matching a token may, as a side
   effect, also bring the parser into a different start condition.

   Implementation note: in this case, this scanner uses:
   - the C_COMMENT start condition when the scanner is within a
     comment

   - the C_INCLUDE start condition when the scanner is within an
     "include" statement

   - the default start condition (INITIAL) in all other cases

   - both C_COMMENT and C_INCLUDE conditions above are exclusive, so
     untagged regular expressions are enabled only in the INITIAL
     state.
*/

/* Another useful thing that can appear in the definition section of a
   .l file, although it is unused here, is a set of "name definitions"
   (see Section 5.1 of the manual).

   A name definition works like a macro definition in C.  It basically
   gives a name to a regular expression.  The name can then be used
   (enclosed in braces) as a shortcut in the second section of a .l
   file, to build more complex regular expressions in a readable way.
   Unlike the C pre-processor, flex automatically places parentheses
   around definitions to properly deal with regular expression
   operators precedence.

   For instance, a definition like
   DIGIT [0-9]

   gives the name 'DIGIT' to a regular expression that matches a
   single digit from 0 to 9 inclusive.  In the second section of the
   file we can then write

   {DIGIT}+

   to match one or more (due to the + operator) consecutive digits
   (due to the expansion of DIGIT).  This is equivalent to, but more
   readable than

   [0-9]+

   especially when it appears multiple time in a complex regular
   expression.

   Implementation note: what about making the CPAL regular expressions
   more readable as an exercise, after we have a working scanner?
*/
/* This is the separator that introduces the second section of the file */
#line 944 "parser/cpal_lex.c"

#define INITIAL 0
#define C_COMMENT 1
#define C_INCLUDE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

/* %if-c-only */

static int yy_init_globals ( yyscan_t yyscanner );

/* %endif */

/* %if-reentrant */

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* %endif */

/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* %if-bison-bridge */

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
/* %% [7.0] user's declarations go here */
#line 226 "parser/cpal_lex.l"



#line 1290 "parser/cpal_lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 219 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 405 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 87 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 87 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 88 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 229 "parser/cpal_lex.l"
{ parser_new_coment(env) ; BEGIN(C_COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 230 "parser/cpal_lex.l"
{ parser_close_coment(env);BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 231 "parser/cpal_lex.l"
{ parser_add_to_comment(env,yytext);}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 232 "parser/cpal_lex.l"
{ parser_add_to_comment(env,"\n"); env->pctx->lineno++; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 233 "parser/cpal_lex.l"
{ parser_add_to_comment(env,"\r");parser_add_to_comment(env,"\n");env->pctx->lineno++; }
	YY_BREAK
case YY_STATE_EOF(C_COMMENT):
#line 234 "parser/cpal_lex.l"
{ parser_failure(env, 888, env->pctx->parseFilename, parser_lineno(env), NULL, "Unclosed comment\n" );
                     exit( 1 );
					}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 237 "parser/cpal_lex.l"
{BEGIN(C_INCLUDE);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 238 "parser/cpal_lex.l"
/* eat the whitespace */
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 239 "parser/cpal_lex.l"
{yytext[strlen(yytext)-1]='\0'; include(yyscanner,env,yytext+1); /* remove leadind and trailing double quote */}     
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 240 "parser/cpal_lex.l"
{parser_warning(env->pctx->parseFilename, parser_lineno(env), NULL, "deprecated include syntax, use double quote string : include \"%s\"\n", yytext); 
				include(yyscanner,env,yytext);
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 243 "parser/cpal_lex.l"
{parser_failure(env, 51, env->pctx->parseFilename, parser_lineno(env), NULL, "Missing terminating \" character\n");}     
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(C_INCLUDE):
#line 246 "parser/cpal_lex.l"
{
         		if (env->pctx->include_stack_ptr>=0)
         		{
         		    
         		    FREE(env->pctx->include_stack_filenames[env->pctx->include_stack_ptr]);
         		}
                 if ( --env->pctx->include_stack_ptr < 0 )
                     {
                     /*leave at 0 for futur files parse*/
                     env->pctx->include_stack_ptr = 0;
                     yyterminate();
                     }
     
                 else
                     {
                     fclose(yyin);
                     yy_delete_buffer( YY_CURRENT_BUFFER ,yyscanner);
                     env->pctx->lineno = env->pctx->line_no_save[env->pctx->include_stack_ptr]  ;
                     strncpy(env->pctx->parseFilename,env->pctx->include_stack_filenames[env->pctx->include_stack_ptr], MAX_PATH);
                     env->program->root = env->pctx->include_stack_nodes[env->pctx->include_stack_ptr];
                     yy_switch_to_buffer(
                          (YY_BUFFER_STATE)env->pctx->include_stack_buffer[env->pctx->include_stack_ptr] ,yyscanner);
                     
                     }
                 }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 274 "parser/cpal_lex.l"
;
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 275 "parser/cpal_lex.l"
{ 
                               if (strlen(yytext+1)<MAX_LINE) {
                                   strncpy(env->pctx->scanned_line, yytext+1, MAX_LINE); /* save the next line */
								   env->pctx->lineno++;
                                   yyless(1);      /* give back all but the \n to rescan */
                                } else {
                                   parser_failure(env, 51, env->pctx->parseFilename, parser_lineno(env), NULL, "Max line length exceeded!\n"); 
                                }
                            }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 284 "parser/cpal_lex.l"
{ 
                                if (strlen(yytext+1)<MAX_LINE) {
                                    strncpy(env->pctx->scanned_line, yytext+1, MAX_LINE); /* save the next line */
                                    env->pctx->lineno++;
                                    yyless(1);      /* give back all but the \n to rescan */
                                } else {
                                   parser_failure(env, 51, env->pctx->parseFilename, parser_lineno(env), NULL, "Max line length exceeded!\n");
                                }
                            }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 293 "parser/cpal_lex.l"
return TKOUT;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 294 "parser/cpal_lex.l"
return TKIN;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 295 "parser/cpal_lex.l"
{yylval->val = AST_makeBooleanNode(env->program,1, yylineno); return BOOLEAN;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 296 "parser/cpal_lex.l"
{yylval->val = AST_makeBooleanNode(env->program,0, yylineno); return BOOLEAN;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 297 "parser/cpal_lex.l"
return TCONST;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 298 "parser/cpal_lex.l"
return TENUM;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 299 "parser/cpal_lex.l"
return TSTRUCT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 300 "parser/cpal_lex.l"
return TVAR;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 301 "parser/cpal_lex.l"
return TCHANNEL;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 302 "parser/cpal_lex.l"
return TQUEUE;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 303 "parser/cpal_lex.l"
return TSTACK;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 304 "parser/cpal_lex.l"
return FOR;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 305 "parser/cpal_lex.l"
return IF;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 306 "parser/cpal_lex.l"
return ELSE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 307 "parser/cpal_lex.l"
return WHILE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 308 "parser/cpal_lex.l"
return TPROCESS;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 309 "parser/cpal_lex.l"
return TKPROCESSDEF;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 310 "parser/cpal_lex.l"
return TTO;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 311 "parser/cpal_lex.l"
return TON;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 312 "parser/cpal_lex.l"
return TAFTER;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 313 "parser/cpal_lex.l"
return TSTATE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 314 "parser/cpal_lex.l"
return TSTATIC;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 315 "parser/cpal_lex.l"
return TCOMMON;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 316 "parser/cpal_lex.l"
return TFINALLY;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 317 "parser/cpal_lex.l"
return TMOD;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 318 "parser/cpal_lex.l"
return TLOOP;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 319 "parser/cpal_lex.l"
return TOVER;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 320 "parser/cpal_lex.l"
{yylval->val = defExpr_makeSymbol(env,yytext,yylineno); return BREAK;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 321 "parser/cpal_lex.l"
{yylval->val = defExpr_makeSymbol(env,yytext,yylineno); return CONTINUE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 322 "parser/cpal_lex.l"
return TWITH;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 323 "parser/cpal_lex.l"
return TAND;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 324 "parser/cpal_lex.l"
return TOR;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 325 "parser/cpal_lex.l"
return T__LINE__;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 326 "parser/cpal_lex.l"
return THERTZ;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 327 "parser/cpal_lex.l"
return TBITWISEAND;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 328 "parser/cpal_lex.l"
return TBITWISEOR;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 329 "parser/cpal_lex.l"
return TBITWISENOT;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 330 "parser/cpal_lex.l"
return TBITWISEXOR;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 331 "parser/cpal_lex.l"
return TBITWISELEFTSHIFT;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 332 "parser/cpal_lex.l"
return TBITWISERIGHTSHIFT;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 333 "parser/cpal_lex.l"
return TEQUAL;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 334 "parser/cpal_lex.l"
return TCEQ;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 335 "parser/cpal_lex.l"
return TCNE;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 336 "parser/cpal_lex.l"
return TNOT;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 337 "parser/cpal_lex.l"
return TCLE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 338 "parser/cpal_lex.l"
return TCGE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 339 "parser/cpal_lex.l"
return TCLT;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 340 "parser/cpal_lex.l"
return TCGT;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 341 "parser/cpal_lex.l"
return TLPAREN;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 342 "parser/cpal_lex.l"
return TRPAREN;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 343 "parser/cpal_lex.l"
return TLBRACE;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 344 "parser/cpal_lex.l"
return TRBRACE;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 345 "parser/cpal_lex.l"
return TLBRACKET;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 346 "parser/cpal_lex.l"
return TRBRACKET;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 347 "parser/cpal_lex.l"
return TDOT;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 348 "parser/cpal_lex.l"
return TCOMMA;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 349 "parser/cpal_lex.l"
return TPLUS;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 350 "parser/cpal_lex.l"
return TMINUS;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 351 "parser/cpal_lex.l"
return TMUL;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 352 "parser/cpal_lex.l"
return TDIV;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 353 "parser/cpal_lex.l"
return TSEMICOLON;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 354 "parser/cpal_lex.l"
return TCOLON;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 355 "parser/cpal_lex.l"
return TAROBASE;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 356 "parser/cpal_lex.l"
return TDOLLAR;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 357 "parser/cpal_lex.l"
{ yylval->val = defExpr_makeTimeLiteral(env, yytext, yylineno); return TIME; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 358 "parser/cpal_lex.l"
{ yylval->val = defExpr_makeFrequencyLiteral(env, yytext, yylineno); return FREQ; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 359 "parser/cpal_lex.l"
{yylval->val = defExpr_makeFloatLiteralNode(env,yytext, yylineno); return FLOAT;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 360 "parser/cpal_lex.l"
{uint64_t value; sscanf(yytext, "%"SCNx64, &value); yylval->val = AST_makeIntegerNode(env->program,value, yylineno); return INTEGER;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 361 "parser/cpal_lex.l"
{yylval->val = defExpr_makeSymbol(env,yytext,yylineno); return SYMBOL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 362 "parser/cpal_lex.l"
{yylval->val = defExpr_makeFloatLiteralNode(env,yytext, yylineno); return FLOAT;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 363 "parser/cpal_lex.l"
{uint64_t value; sscanf(yytext, "%"SCNu64, &value); yylval->val = AST_makeIntegerNode(env->program,value, yylineno); return INTEGER;}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 364 "parser/cpal_lex.l"
{yytext[strlen(yytext)-1]='\0'; yylval->val = defExpr_makeStr(env,yytext+1,yylineno);  return STRING;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 365 "parser/cpal_lex.l"
parser_failure(env, 300, env->pctx->parseFilename, parser_lineno(env), NULL, "unknown token!\n"); 
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 367 "parser/cpal_lex.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1875 "parser/cpal_lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 219 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
/* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 219 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 218);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

/* %% [19.0] update BOL and yylineno */
	if ( c == '\n' )
		
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
/* %if-c-only */
void yypop_buffer_state (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/* %endif */

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/* %if-reentrant */

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* Accessor methods for yylval and yylloc */

/* %if-bison-bridge */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* %endif */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

/* %if-reentrant */
    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 367 "parser/cpal_lex.l"

/* The separator above starts the third section of the file, which contains
   user code.
*/

/* Implementation note: We should think more carefully about the
   following two functions, yyerror and scan_string.  Contrary to what I
   said at first (sorry) this is an error function, but is appartently
   used by the parser rather than the scanner.  So it is not completely
   clear to me what is it doing here.  The second function seems to be
   unused, and there is no prototype in the first section of this .l
   file.
*/

void yyerror(yyscan_t scanner, parser_Env *env, const char *s)
{
     parser_failure(env, 301, env->pctx->parseFilename, parser_lineno(env), NULL, "%s before \"%s\" in this line:\n%s\n", s, yyget_text(scanner), env->pctx->scanned_line);
}

void scan_string(yyscan_t scanner, char* str)
{
	YY_BUFFER_STATE buf = yy_scan_string(str,scanner);
    yy_switch_to_buffer(buf,scanner);

}

/* Implementation note: The next function is related to including files at the
   scanner level, by far the most complex part of the scanner.  It
   deserves a discussion by itself, also because we need to talk about
   scanner buffers and how to switch the scanner input from one buffer to
   another.  I should study this a little bit more.
*/

/* I TBD: Temporary implementation of include() that only creates a
   AST_CODE_STATEMENT node with enum statement_type INCLUDE_OP,
   without actually including and parsing the file.  As in the
   original definition of this kind of node, the name of the included
   file (unresolved in this implementation) is held as a
   AST_CODE_STRING in .part2 of the AST_CODE_STATEMENT.

   Remove when we handle include completely.
*/

void include(yyscan_t scanner, parser_Env * env, char * text)
{
    /* This is a bit questionable, but it is useful to access
       the scanner context, for instance, to handle
       yylineno properly.
    */
    struct yyguts_t * yyg = (struct yyguts_t*)scanner;

    /* Create the AST_CODE_STRING that holds the file name */
    AST *include_name_node = defExpr_makeLabelStr(env, text, parser_lineno(env));

    /* Create the AST_CODE_STATEMENT/INCLUDE_OP node, link
       include_name_node as part2, add to the list of external
       definition of this compilation unit.
    */
    parser_add_external_definition(env,
        AST_makeNode(env->program, INCLUDE_OP, 0, NULL, include_name_node, yylineno));

    /* Reset the scanner to the normal state, the include put it in
       C_INCLUDE
    */
    BEGIN(INITIAL);
}

#if 0
void include(yyscan_t scanner, parser_Env * env, char * text) { 
	char * actualPath = NULL;
	int already_included =0;
	int i;
	AST * include_name_node =  defExpr_makeLabelStr(env,text,parser_lineno(env));
    struct yyguts_t * yyg = (struct yyguts_t*)scanner;
	if ( env->pctx->include_stack_ptr >= MAX_INCLUDE_DEPTH )
	{
	     parser_failure(env, 301, env->pctx->parseFilename, parser_lineno(env), NULL, "Includes nested too deeply\n" );
	     exit( 1 );
	}
	switch(lookupFilePath(text,
						env->pctx->parseFilename,
						env->pctx->parser_include_path,&actualPath)) {
	  case LfpFound: {
	    char absPath[MAX_PATH];
	    (void)get_full_path(actualPath,absPath);
	    for (i=0;i<env->pctx->include_ptr;i++)
        {
          if (strcmp(absPath,env->pctx->already_included_files[i])==0)
	      {
            already_included=1;
          }
        }
        if (!already_included)
		{
			env->pctx->already_included_files[env->pctx->include_ptr] = malloc(MAX_PATH+1);
			strncpy(env->pctx->already_included_files[env->pctx->include_ptr],absPath,MAX_PATH);
			env->pctx->include_ptr++;
			env->pctx->include_stack_filenames[env->pctx->include_stack_ptr]= malloc(MAX_PATH+1);
			strncpy(env->pctx->include_stack_filenames[env->pctx->include_stack_ptr],env->pctx->parseFilename,MAX_PATH);
			env->pctx->include_stack_buffer[env->pctx->include_stack_ptr] = (void * )YY_CURRENT_BUFFER;
			env->pctx->include_stack_nodes[env->pctx->include_stack_ptr] = env->program->root;
			env->pctx->include_stack_ptr++;
			yyin = fopen(actualPath, "r");
			if (!yyin)
			{
			   parser_failure(env, 301, env->pctx->parseFilename, parser_lineno(env), NULL, "%s no such include file\n", text);
			}
			else
			{
			  strncpy(env->pctx->parseFilename,absPath, MAX_PATH);
			  env->pctx->line_no_save[env->pctx->include_stack_ptr-1] = env->pctx->lineno;
			  env->pctx->lineno = 1;
			  AST * include_node = AST_makeNode(env->program,INCLUDE_OP, 0, NULL, include_name_node, yylineno); 
			  parser_add_external_definition(env, include_node); 
		      env->program->root = include_node;
			        
			  yy_switch_to_buffer(
			      yy_create_buffer( yyin, YY_BUF_SIZE ,scanner),scanner );                            
			  BEGIN(INITIAL);
		    }
	    }
	    else /*already included skip */
	    {
			BEGIN(INITIAL);
	    }
      } break;
      case LfpNotFound: {
        parser_failure(env, 301, env->pctx->parseFilename, parser_lineno(env), NULL, "%s no such include file\n", text);
        BEGIN(INITIAL);
	  } break;
      case LfpFileNameTooLong: {
        parser_failure(env, 302, env->pctx->parseFilename, parser_lineno(env), NULL, "Maximum file name size overflow\n");
        BEGIN(INITIAL);
      } break;      
    }
    free(actualPath);
 }
#endif

/* This is a replacement for the flex-provided dynamic memory
   allocation function.  Unlike include() above, no prototype is needed
   in the first section, because this function is known to, and used by,
   flex.  So, it provides the prototype by itself.
*/

void *yyalloc (size_t  size , void * yyscanner)
{
        return (void *) calloc( size ,1);
}

